const errorCodes = {
  // 공통 에러 
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  DUPLICATE_RESOURCE: 'DUPLICATE_RESOURCE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',

  // 유저 관련 
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  INVALID_EMAIL_FORMAT: 'INVALID_EMAIL_FORMAT',
  INVALID_PASSWORD_FORMAT: 'INVALID_PASSWORD_FORMAT',
  INVALID_BIRTHDATE_FORMAT: 'INVALID_BIRTHDATE_FORMAT',
  INVALID_PAIN_AREA_ID_FORMAT: 'INVALID_PAIN_AREA_ID_FORMAT',
  PAINAREA_NOT_FOUND: 'PAINAREA_NOT_FOUND',

  // 게시글 관련 
  POST_NOT_FOUND: 'POST_NOT_FOUND',
  NO_PERMISSION: 'NO_PERMISSION',

  // 로그인 관련
  INVALID_REQUEST: 'INVALID_REQUEST',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',  // 이메일 또는 비밀번호가 올바르지 않을 때 사용

};

export default errorCodes;
