const errorCodes = {
  // 공통 에러 (000~099)
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  DUPLICATE_RESOURCE: 'DUPLICATE_RESOURCE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  // 유저 관련 (100~199)
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  INVALID_EMAIL_FORMAT: 'INVALID_EMAIL_FORMAT',
  INVALID_PASSWORD_FORMAT: 'INVALID_PASSWORD_FORMAT',
  INVALID_BIRTHDATE_FORMAT: 'INVALID_BIRTHDATE_FORMAT',

  // 게시글 관련 (200~299)
  POST_NOT_FOUND: 'POST_NOT_FOUND',
  NO_PERMISSION: 'NO_PERMISSION'
};

export default errorCodes;
