const errorCodes = {
  // 공통 에러 (000~099)
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  DUPLICATE_RESOURCE: 'DUPLICATE_RESOURCE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  // 유저 관련 (100~199)
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',

  // 게시글 관련 (200~299)
  POST_NOT_FOUND: 'POST_NOT_FOUND',
  NO_PERMISSION: 'NO_PERMISSION',

  // 병원 관련 (300~399)
  HOSPITAL_NOT_FOUND: 'HOSPITAL_NOT_FOUND',
  INVALID_COORDINATES: 'INVALID_COORDINATES',
  INVALID_LIMIT: 'INVALID_LIMIT'
};

export default errorCodes;
