name: CI - Pull Request

on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - dev

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Node.js 설정
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: 의존성 설치
        run: npm ci

      - name: Prisma Client 생성
        run: npm run prisma:generate
      - name: Validate Prisma Schema
        run: |
          npx prisma migrate diff \
            --from-empty \
            --to-schema-datamodel \
            --exit-code
